prod:
  image: vizzuality/rw_layerspec:2.1.0${STAGING}
  env_file: prod.env

  command: start
  restart: always
  ports:
    - '3030'

  dns: ${DNS_SERVER}

  log_driver: "syslog"
  log_opt:
    syslog-address: ${SYSLOG_ADDRESS}
    tag: rw_layerspec${STAGING}

  links:
    - redis

redis:
  image: redis
  container_name: redis_rw_layerspec
  restart: always
