prod:
  image: vizzuality/rw_layerspec:1.0.0${STAGING}
  command: start
  ports:
    - '3030'
  env_file: prod.env

  log_driver: "gelf"
  restart: always
  log_opt:
    gelf-address: ${GELF_ADDRESS}
