prod:
  image: vizzuality/rw_layerspec:1.0.0${STAGING}
  command: start
  ports:
    - '3030'
  links:
    - redis
  env_file: prod.env

  log_driver: "gelf"
  restart: always
  log_opt:
    gelf-address: ${GELF_ADDRESS}

redis:
  image: redis
  container_name: redis_rw_layerspec
  restart: always
