test:
  build: .
  command: test
  volumes:
    - .:/rw_layerspec
  links:
    - mongo
  env_file: test.env

mongo:
  image: mongo
  container_name: layerspec-mongo-test
  command: --smallfiles
  ports:
    - '27017'
