development:
  clients:
    default:
      database: rw_layerspec_development
      hosts:
        - <%= ENV['LAYERSPEC_MONGO_PORT_27017_TCP_ADDR'] %>:<%= ENV['MONGO_PORT_27017_TCP_PORT'] %>
      options:
        user: <%= ENV['MONGO_PORT_27017_TCP_USER']%>
        password: <%= ENV['MONGO_PORT_27017_TCP_PASS']%>
        read:
          mode: :primary
        max_pool_size: 1

test:
  clients:
    default:
      database: rw_layerspec_test
      hosts:
        - <%= ENV['MONGO_PORT_27017_TCP_ADDR'] %>:<%= ENV['MONGO_PORT_27017_TCP_PORT'] %>
      options:
        user: <%= ENV['MONGO_PORT_27017_TCP_USER']%>
        password: <%= ENV['MONGO_PORT_27017_TCP_PASS']%>
        read:
          mode: :primary
        max_pool_size: 1

staging:
  clients:
    default:
      database: <%= ENV['MONGO_PORT_27017_TCP_DB'] %>
      hosts:
        - <%= ENV['MONGO_PORT_27017_TCP_ADDR'] %>:<%= ENV['MONGO_PORT_27017_TCP_PORT'] %>
      options:
        user: <%= ENV['MONGO_PORT_27017_TCP_USER']%>
        password: <%= ENV['MONGO_PORT_27017_TCP_PASS']%>
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      database: <%= ENV['MONGO_PORT_27017_TCP_DB'] %>
      hosts:
        - <%= ENV['MONGO_PORT_27017_TCP_ADDR'] %>:<%= ENV['MONGO_PORT_27017_TCP_PORT'] %>
      options:
        user: <%= ENV['MONGO_PORT_27017_TCP_USER']%>
        password: <%= ENV['MONGO_PORT_27017_TCP_PASS']%>
        read:
          mode: :primary
        max_pool_size: 1
